# Generated by Django 4.0.1 on 2022-07-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freight',
            name='consignment_id',
        ),
        migrations.AddField(
            model_name='freight',
            name='consignmentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignmentid', to='api.consignment'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='api.customer'),
        ),
    ]
