# Generated by Django 4.0.1 on 2022-07-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_freight_consignment_id_freight_consignmentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freight',
            name='consignmentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignmentid', to='api.consignment'),
        ),
    ]
