# Generated by Django 4.0.1 on 2022-07-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_freight_consignmentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freight',
            name='consignmentid',
        ),
    ]
