# Generated by Django 4.0.1 on 2022-07-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_freight_consignmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='consignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignment', to='api.consignment'),
        ),
    ]
