# Generated by Django 4.0.1 on 2022-09-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_transfer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='isPaid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
