# Generated by Django 4.0.1 on 2022-07-26 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_freight_consignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='freight',
            name='amount_sent_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freight',
            name='payment_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
        ),
    ]
