# Generated by Django 4.0.1 on 2022-09-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_freight_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='note',
            field=models.CharField(blank=True, default='Note', max_length=255, null=True),
        ),
    ]
