# Generated by Django 4.0.1 on 2022-07-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_freight_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='picked_up',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
