# Generated by Django 4.0.1 on 2022-08-01 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_freight_picked_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freight',
            name='amount_sent_dollars',
        ),
    ]
